### ISSUE TITLE
Fast access to URLs

### ISSUE THREAD

**Issue by CrashLaker** [apankrat/nullboard#16]
Hi @apankrat,

Great project you've just built!! Really enjoying it!

One use I want to have on this is as a bookmark store/manager.
By saying that I'm wondering if it's possible to have a fast access to a URL pasted just by clicking on it or Ctrl+Clicking or it.

Regards,
C.

**Comment by apankrat** [comment]
Cheers, thanks for the kind words. Let me see what I can do.

**Comment by apankrat** [comment]
Done. Added two things:

Links will "pulse" on hover and can be opened via the right-click menu. Left-clicking on them will still work as before - it will start the text edit. This is by design, see below.

![](https://nullboard.io/images/nullboard-links-on-hover.gif)

Pressing `CapsLock` will highlight links in blue and make them left-clickable.

![](https://nullboard.io/images/nullboard-links-reveal.gif)

**Comment by CrashLaker** [comment]
awesome! thank you!!

**Comment by CrashLaker** [comment]
Hi @apankrat 

Not to bother too much but when the link is too long it get's weird.
![chrome-capture](https://user-images.githubusercontent.com/4432491/74935777-a29cbe00-53c7-11ea-94ab-1335caa4cd63.gif)

I could increase the width but even though.
![image](https://user-images.githubusercontent.com/4432491/74935717-7ed97800-53c7-11ea-9fa0-d46c63dc1c70.png)

If we could write it in markdown syntax it would be great :D

**Comment by apankrat** [comment]
Ah, good catch. That's not URL-specific per se. I pushed the patch just now, please check if it resolves the issue.
