### ISSUE TITLE
FR: allow to overwrite an existing board on import

### ISSUE THREAD

**Issue by gf-mse** [apankrat/nullboard#62]
After importing a saved revision of the same board, it is automagically assigned a new board id, what leaves us with two identical board names in the menu; if the issue is not attended immediately, then it is up to us as the user to figure out which is which, and makes the whole thing a little confusing.

I wonder what if we would allow the user to _choose_ if the existing board shall be overwritten on import -- something along the lines of the following ([982e26384f](https://github.com/gf-mse/nullboard/commit/982e26384f73b07cdd117dbebf80b1b551d78885))?

I can easily make a PR if required ))

**Comment by apankrat** [comment]
Good catch. There are two ways to address this.

1. Keep the logic as is, but append, say, `imported on yyyy-mm-dd` to the board name, so to resolve the ambiguity.
2. Ask what to do.

I think #2 is cleaner, but the issue here is that the prompt will need 3 options - overwrite, create (with a new ID) or cancel, so if we are to stick to the stock UI, it will need to be either a `prompt` (with explicit input) or a couple of `confirm`s. The latter is probably better. I will make the change and let's see if it's workable.

**Comment by apankrat** [comment]
Done as https://github.com/apankrat/nullboard/commit/a456a76aa7ab8c9174952477aa28cc5e3e718e4a

**Comment by apankrat** [comment]
... and I'll close it for now.
